version: "3"

networks:
    web:
        external: true
    internal:
        external: false

services:
    portfolio:
        image: haidousm/portfolio:1.0.0
        labels:
            - traefik.http.routers.portfolio.rule=Host(`moussa.codes`)
            - traefik.http.routers.portfolio.tls=true
            - traefik.http.routers.portfolio.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - internal
            - web
